name: CI

on: [push]

jobs:
  test:
    steps:
      - uses: actions/setup-node@v2
      - name: Setup Yarn
        run: npm install -g yarn
        run: yarn install
        run: yarn test
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
